version: '3.8'

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network
    volumes:
      - plugin-data:/usr/src/app/generated-plugins
    environment:
      - PORT=3001
      - API_HOST=${API_HOST:-http://host.docker.internal:5000}
      - SCRIPT_PATH=/usr/src/app/bash.sh
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
    extra_hosts:
      # This allows containers to communicate with the host machine
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  api-service:
    networks:
      - app-network

volumes:
  plugin-data:

networks:
  app-network:
    driver: bridge
