services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - api-network
    volumes:
      - plugin-data:/usr/src/app/generated-plugins
    environment:
      - PORT=3001
      - API_HOST=http://gemni-api-gemini-api-1:5000  # Use the exact container name
      - SCRIPT_PATH=/app/bash.sh
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - API_TOKEN=${API_TOKEN}
    restart: unless-stopped

volumes:
  plugin-data:

networks:
  api-network:
    external: false  # Create the network as part of this compose
    driver: bridge