version: '3.8'

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network
    volumes:
      - plugin-data:/usr/src/app/generated-plugins
    environment:
      - PORT=3001
      - API_HOST=http://gemini-api:5000
      - SCRIPT_PATH=/app/bash.sh
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
      # Add these environment variables
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - API_TOKEN=${API_TOKEN}
    restart: unless-stopped
    external_links:
      - gemni-api-gemini-api-1:gemini-api  # Using hyphens, not underscores

volumes:
  plugin-data:

networks:
  app-network:
    external: true
    name: gemni-api-default  # Using hyphens, not underscores