version: '3'

services:
  api-server:
    build: .
    container_name: minecraft-plugin-api
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - SCRIPT_PATH=/app/bash.sh
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,https://46.247.108.139:3001,http://46.247.108.139:3001,https://46.247.108.139,http://46.247.108.139
    volumes:
      - plugin-data:/app/generated-plugins
    restart: unless-stopped

volumes:
  plugin-data: